---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: version
- name: git
- name: git-ci
- name: git-main

outputs:
- name: gh
- name: notifications
- name: git-main
- name: git-ci

params:
  REPO_ROOT:        git
  VERSION_FROM:     version/number
  RELEASE_ROOT:     gh
  NOTIFICATION_OUT: notifications
  BRANCH:           master
  GITHUB_OWNER:     genesis-community
  GIT_EMAIL:        ci@starkandwayne.com
  GIT_NAME:         Stark & Wayne CI Bot
  KIT_SHORTNAME:    concourse

run:
  path: git-ci/ci/tasks/shipit/task