---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse-ruby
    tag: '1.14'

inputs:
- name: git
  path: kit
- name: git-ci
- name: bats
- name: work
- name: vsphere-stemcell

run:
  path: git-ci/ci/tasks/bats/task

params:
  BAT_DEBUG_MODE:         false
